# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('georace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='event',
            name='geoloc',
        ),
        migrations.AddField(
            model_name='event',
            name='geotag',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
